repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.812"
    hooks:
      - files: ^codeline/
        id: mypy
        stages: [commit]
        types: [file, python]
  - repo: local
    hooks:
      - id: tox
        name: tox
        entry: tox
        language: system
        pass_filenames: false
        stages: [commit]
      - files: ^codeline/
        id: pylint
        name: pylint
        entry: pylint
        language: system
        stages: [commit]
        types: [file, python]
