name: Full Tests
on: [push, pull_request]

jobs:
  lint:
    name: Lint Source Code
    runs-on: ubuntu-latest
    steps:
      - name: Todo
        run: echo "todo"
  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Todo
        run: echo "todo"
  integration-test:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Todo
        run: echo "todo"