name: Full Tests
on:
  push:
    branches: [main, release/*]
  pull_request:
    branches: [main, release/*]

jobs:
  lint:
    name: Lint Source Code
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Pylint
        run: pip install pylint
      - name: Install MyPy
        run: pip install mypy
      - name: Run Pylint
        run: python -m pylint codeline
      - name: Run MyPy
        run: python -m mypy codeline
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache tox
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ./.tox/py39
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install Tox
        run: pip install tox
      - name: Tox
        run: tox
